import 'package:boi_flutter/components/horizontal_list.dart';
import 'package:flutter/material.dart';
import 'package:boi_flutter/model/beneficiary_model.dart';

class BankTransfer extends StatelessWidget {
  BankTransfer({super.key});

  final List<dynamic> favBeni = [];

  @override
  Widget build(BuildContext context) {
    final list = FetchJson();
    print('dddd');
    print(list);

    PrintName(clickedItem) => {print(clickedItem)};

    return Scaffold(
      appBar: AppBar(
        title: const Text('Bank Transfer'),
      ),
      body: (Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          HorizontalList(title: 'ddd', onPressItem: PrintName, listData: [
            {
              "foreignRemittanceModel": null,
              "beneficiaryId": "1811",
              "accountNumber": "44444444444444444444",
              "name": "van",
              "nickName": "van",
              "image": null,
              "encodedImg": null,
              "imgExtension": null,
              "bank": "AXIS BANK",
              "branch": "HYDERABAD",
              "accountType": null,
              "schemeCode": null,
              "status": "Active",
              "ifscCode": "UTIB0000008",
              "limit": 50007.0,
              "favourite": true,
              "confirmationCode": null,
              "upiId": null,
              "custUpiNumber": null,
              "phoneNumber": null,
              "currency": null,
              "customerId": "144795470",
              "transferType": null,
              "bankLogo": null,
              "mmid": null,
              "mmidNumber": null,
              "upiNumber": null,
              "isWithinBoi": false,
              "isBlackListed": null,
              "freezeCode": null,
              "siActive": false
            },
            {
              "foreignRemittanceModel": null,
              "beneficiaryId": "2693",
              "accountNumber": null,
              "name": null,
              "nickName": "rrrr",
              "image": null,
              "encodedImg": null,
              "imgExtension": null,
              "bank": null,
              "branch": null,
              "accountType": null,
              "schemeCode": null,
              "status": "Active",
              "ifscCode": null,
              "limit": 10000.0,
              "favourite": true,
              "confirmationCode": null,
              "upiId": null,
              "custUpiNumber": null,
              "phoneNumber": null,
              "currency": null,
              "customerId": "144795470",
              "transferType": null,
              "bankLogo": null,
              "mmid": "6666666",
              "mmidNumber": "66666666666",
              "upiNumber": null,
              "isWithinBoi": false,
              "isBlackListed": null,
              "freezeCode": null,
              "siActive": false
            },
            {
              "foreignRemittanceModel": null,
              "beneficiaryId": "2693",
              "accountNumber": null,
              "name": null,
              "nickName": "rrrr",
              "image": null,
              "encodedImg": null,
              "imgExtension": null,
              "bank": null,
              "branch": null,
              "accountType": null,
              "schemeCode": null,
              "status": "Active",
              "ifscCode": null,
              "limit": 10000.0,
              "favourite": true,
              "confirmationCode": null,
              "upiId": null,
              "custUpiNumber": null,
              "phoneNumber": null,
              "currency": null,
              "customerId": "144795470",
              "transferType": null,
              "bankLogo": null,
              "mmid": "6666666",
              "mmidNumber": "66666666666",
              "upiNumber": null,
              "isWithinBoi": false,
              "isBlackListed": null,
              "freezeCode": null,
              "siActive": false
            },
            {
              "foreignRemittanceModel": null,
              "beneficiaryId": "2693",
              "accountNumber": null,
              "name": null,
              "nickName": "rrrr",
              "image": null,
              "encodedImg": null,
              "imgExtension": null,
              "bank": null,
              "branch": null,
              "accountType": null,
              "schemeCode": null,
              "status": "Active",
              "ifscCode": null,
              "limit": 10000.0,
              "favourite": true,
              "confirmationCode": null,
              "upiId": null,
              "custUpiNumber": null,
              "phoneNumber": null,
              "currency": null,
              "customerId": "144795470",
              "transferType": null,
              "bankLogo": null,
              "mmid": "6666666",
              "mmidNumber": "66666666666",
              "upiNumber": null,
              "isWithinBoi": false,
              "isBlackListed": null,
              "freezeCode": null,
              "siActive": false
            },
            {
              "foreignRemittanceModel": null,
              "beneficiaryId": "2693",
              "accountNumber": null,
              "name": null,
              "nickName": "rrrr",
              "image": null,
              "encodedImg": null,
              "imgExtension": null,
              "bank": null,
              "branch": null,
              "accountType": null,
              "schemeCode": null,
              "status": "Active",
              "ifscCode": null,
              "limit": 10000.0,
              "favourite": true,
              "confirmationCode": null,
              "upiId": null,
              "custUpiNumber": null,
              "phoneNumber": null,
              "currency": null,
              "customerId": "144795470",
              "transferType": null,
              "bankLogo": null,
              "mmid": "6666666",
              "mmidNumber": "66666666666",
              "upiNumber": null,
              "isWithinBoi": false,
              "isBlackListed": null,
              "freezeCode": null,
              "siActive": false
            },
            {
              "foreignRemittanceModel": null,
              "beneficiaryId": "2693",
              "accountNumber": null,
              "name": null,
              "nickName": "rrrr",
              "image": null,
              "encodedImg": null,
              "imgExtension": null,
              "bank": null,
              "branch": null,
              "accountType": null,
              "schemeCode": null,
              "status": "Active",
              "ifscCode": null,
              "limit": 10000.0,
              "favourite": true,
              "confirmationCode": null,
              "upiId": null,
              "custUpiNumber": null,
              "phoneNumber": null,
              "currency": null,
              "customerId": "144795470",
              "transferType": null,
              "bankLogo": null,
              "mmid": "6666666",
              "mmidNumber": "66666666666",
              "upiNumber": null,
              "isWithinBoi": false,
              "isBlackListed": null,
              "freezeCode": null,
              "siActive": false
            },
            {
              "foreignRemittanceModel": null,
              "beneficiaryId": "2693",
              "accountNumber": null,
              "name": null,
              "nickName": "rrrr",
              "image": null,
              "encodedImg": null,
              "imgExtension": null,
              "bank": null,
              "branch": null,
              "accountType": null,
              "schemeCode": null,
              "status": "Active",
              "ifscCode": null,
              "limit": 10000.0,
              "favourite": true,
              "confirmationCode": null,
              "upiId": null,
              "custUpiNumber": null,
              "phoneNumber": null,
              "currency": null,
              "customerId": "144795470",
              "transferType": null,
              "bankLogo": null,
              "mmid": "6666666",
              "mmidNumber": "66666666666",
              "upiNumber": null,
              "isWithinBoi": false,
              "isBlackListed": null,
              "freezeCode": null,
              "siActive": false
            },
          ]),
          Text('my fav'),
          Text('send money'),
          Text('recent payments')
        ],
      )),
    );
  }
}
